#!/usr/bin/env python3
"""
gen_doxygen_script.py — Search a directory tree for VHDL files and write a
bash script that runs vhdl_doxygen.py --inplace on each one.

Usage:
    python gen_doxygen_script.py [root_dir] [options]

Examples:
    python gen_doxygen_script.py                            # search current directory
    python gen_doxygen_script.py ~/projects/fpga            # search specific directory
    python gen_doxygen_script.py ~/fpga -o annotate.sh      # custom output script name
    python gen_doxygen_script.py ~/fpga --model gemini-2.5-pro
    python gen_doxygen_script.py ~/fpga --doxygen-script /opt/tools/vhdl_doxygen.py
"""

import argparse
import os
import stat
import sys
from pathlib import Path


VHDL_EXTENSIONS = {".vhd", ".vhdl"}


def find_vhdl_files(root: Path) -> list[Path]:
    """Recursively find all VHDL files under root, sorted for determinism."""
    found = []
    for dirpath, _, filenames in os.walk(root):
        for name in filenames:
            if Path(name).suffix.lower() in VHDL_EXTENSIONS:
                found.append(Path(dirpath) / name)
    return sorted(found)


def write_bash_script(
    vhdl_files: list[Path],
    output_path: Path,
    doxygen_script: str,
    model: str,
    python_exe: str,
    stop_on_error: bool,
    sleep_seconds: float,
) -> None:
    """Write the bash script to output_path."""
    lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by gen_doxygen_script.py",
        "# Runs vhdl_doxygen.py --inplace on every VHDL file found.",
        "#",
        f"# Files found : {len(vhdl_files)}",
        f"# Model       : {model}",
        f"# Generated   : $(date -u '+%Y-%m-%d %H:%M:%S UTC' 2>/dev/null || echo 'unknown')",
        "",
    ]

    if stop_on_error:
        lines += [
            "# Exit immediately if any command fails.",
            "set -euo pipefail",
            "",
        ]
    else:
        lines += [
            "# Continue on error; tally failures at the end.",
            "set +e",
            "FAILURES=0",
            "",
        ]

    lines += [
        "# Verify the doxygen script exists before starting.",
        f'if ! command -v "{python_exe}" &>/dev/null; then',
        f'    echo "ERROR: Python interpreter not found: {python_exe}" >&2',
        "    exit 1",
        "fi",
        f'if [ ! -f "{doxygen_script}" ]; then',
        f'    echo "ERROR: vhdl_doxygen.py not found: {doxygen_script}" >&2',
        "    exit 1",
        "fi",
        "",
        f'echo "Processing {len(vhdl_files)} VHDL file(s) with model: {model}"',
        "",
    ]

    for i, vhdl_path in enumerate(vhdl_files, 1):
        escaped = str(vhdl_path).replace("'", "'\\''")   # single-quote escape
        lines += [
            f'echo "[{i}/{len(vhdl_files)}] {vhdl_path.name}"',
            f"'{python_exe}' '{doxygen_script}' --inplace --model '{model}' '{escaped}'",
        ]
        if not stop_on_error:
            lines += [
                'if [ $? -ne 0 ]; then',
                f'    echo "  FAILED: {escaped}" >&2',
                '    FAILURES=$((FAILURES + 1))',
                'fi',
            ]
        lines.append("")

    if not stop_on_error:
        lines += [
            'if [ "$FAILURES" -gt 0 ]; then',
            '    echo ""',
            '    echo "WARNING: $FAILURES file(s) failed." >&2',
            '    exit 1',
            'fi',
        ]

    lines += [
        'echo ""',
        'echo "Done."',
    ]

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Make the script executable (chmod +x)
    current = output_path.stat().st_mode
    output_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Find all VHDL files in a directory tree and generate a "
                    "bash script to annotate each with Doxygen comments.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "root",
        nargs="?",
        default=".",
        help="Root directory to search (default: current directory)",
    )
    parser.add_argument(
        "-o", "--output",
        default="run_doxygen.sh",
        help="Output bash script filename (default: run_doxygen.sh)",
    )
    parser.add_argument(
        "--doxygen-script",
        default=None,
        help="Path to vhdl_doxygen.py (default: same directory as this script)",
    )
    parser.add_argument(
        "--model",
        default="gemini-2.5-flash",
        help="Model to pass to vhdl_doxygen.py (default: gemini-2.5-flash)",
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python interpreter to use in the bash script "
             "(default: the one running this script)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=2.0,
        metavar="SECONDS",
        help="Seconds to sleep between files to avoid API rate limits "
             "(default: 2, use 0 to disable)",
    )
    parser.add_argument(
        "--stop-on-error",
        action="store_true",
        help="Add 'set -euo pipefail' so the bash script stops on first failure "
             "(default: continue and report failures at the end)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the list of VHDL files found without writing any output",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    root = Path(args.root).expanduser().resolve()
    if not root.exists():
        print(f"Error: directory not found: {root}")
        sys.exit(1)
    if not root.is_dir():
        print(f"Error: not a directory: {root}")
        sys.exit(1)

    # Default doxygen script location: same directory as this script
    if args.doxygen_script:
        doxygen_script = str(Path(args.doxygen_script).expanduser().resolve())
    else:
        doxygen_script = str(Path(__file__).resolve().parent / "vhdl_doxygen.py")

    print(f"Searching : {root}")
    vhdl_files = find_vhdl_files(root)

    if not vhdl_files:
        print("No VHDL files found.")
        sys.exit(0)

    print(f"Found     : {len(vhdl_files)} VHDL file(s)")

    if args.dry_run:
        print()
        for f in vhdl_files:
            print(f"  {f}")
        return

    output_path = Path(args.output)
    write_bash_script(
        vhdl_files=vhdl_files,
        output_path=output_path,
        doxygen_script=doxygen_script,
        model=args.model,
        python_exe=args.python,
        stop_on_error=args.stop_on_error,
    )

    print(f"Written   : {output_path}  (chmod +x applied)")
    print()
    print(f"Run with:  bash {output_path}")


if __name__ == "__main__":
    main()
